WebPlanner/WebPlanner/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebPlanner.Domain.Auxiliary_Models;
using WebPlanner.Domain.Entity;
using WebPlanner.Service.Interfaces;

namespace WebPlanner.Controllers
{
    public sealed class AccountController : Controller
    {
        private readonly IAccountService accountService; 
        public AccountController(IAccountService accountService)
        {
            this.accountService = accountService;
        }
        [Authorize]

        public async Task<IActionResult> SetUpAccount()
        {
            if (User?.Identity?.Name != null)
            {
                var account = await accountService.GetAccountByEmail(User.Identity.Name);
                if (account.StatusCode == Service.ResponseStatus.OK)
                {
                    var userSetup = accountService.CreateUserSettingModel(account.Data);
                    return View(userSetup);
                }
                return RedirectToAction("Error");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> UpdateProfileInformation(UserSettingModel account)
        {
            var updatedAccount = new Account()
            {
                Email = User?.Identity?.Name,
                Name = account.Name,
                Bio = account.Bio,
                URL = account.URL,
                Location = account.Location,
            };
            var resultUpdate = await accountService.UpdateProfileInformation(updatedAccount);
            if (resultUpdate.StatusCode == Service.ResponseStatus.OK)
            {
                return RedirectToAction("SetUpAccount", "Account");
            }
            return RedirectToAction("Error");
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> ChangePassword(UserSettingModel userSettingModel)
        {
            var changeResponse = await accountService.ChangePassword(User?.Identity?.Name, 
                userSettingModel.OldPassword, userSettingModel.NewPassword);
            if (changeResponse.StatusCode == Service.ResponseStatus.OK)
            {
                return RedirectToAction("SetUpAccount", "Account");
            }
            return RedirectToAction("Error");
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AdminPanel()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AdminPanel(string res)
        {
            return View();
        }

    }
}

WebPlanner/WebPlanner/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebPlanner.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult AdminPanel()
        {
            return View();
        }
    }
}

WebPlanner/WebPlanner/Controllers/CashSavingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebPlanner.Controllers
{
    [Authorize]
    public class CashSavingController : Controller
    {
        [HttpGet]        
        public IActionResult Cash()
        {

            return View();
        }
    }
}

WebPlanner/WebPlanner/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebPlanner.Domain.Auxiliary_Models;
using WebPlanner.Service.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using WebPlanner.Domain.Enums;
using WebPlanner.Service.Interfaces.ItemInterfaces;

namespace WebPlanner.Controllers
{
    public class HomeController : Controller
    {
        private readonly IItemGroupServiсe itemGroupService;
        private readonly IAccountService accountService;
        public HomeController(IItemGroupServiсe itemGroupService, IAccountService accountService)
        {
            this.itemGroupService = itemGroupService;
            this.accountService = accountService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserManagerModel model)
        {
            var loginResponse = await accountService.Login(model.LoginEmail, model.LoginPassword);
            if (loginResponse.StatusCode == Service.ResponseStatus.OK && loginResponse.Data is not null)
            {
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(loginResponse.Data));
                if (User.IsInRole(AccountType.User.ToString()))
                {
                    return RedirectToAction("Index", "Home");
                }
                return RedirectToAction("AdminPanel", "Admin");
            }
            else 
            {
                return RedirectToAction("Error");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Register(UserManagerModel model)
        {
            var registerResponse = await accountService.Registration(
                model.RegEmail, model.RegName, model.RegPassword);
            if (registerResponse.StatusCode == Service.ResponseStatus.OK && registerResponse.Data is not null)
            {
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(registerResponse.Data));
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Error");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

WebPlanner/WebPlanner/Controllers/MyDayController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebPlanner.Controllers
{
    public class MyDayController : Controller
    {
        [HttpGet]
        public IActionResult ShowMyDay()
        {


            return View();
        }
    }
}

WebPlanner/WebPlanner/Views/Admin/AdminPanel.cshtml
<!Docktype html>
<html>
    <head>

    </head>
    <body>
        <form>
        Раздел
        <select>
            <option selected="selected">Выберите объект</option>
            <option>Пункт 1</option>
            <option>Пункт 2</option>
        </select><br>
        <input type="button">Добавить новый раздел
        </form>
        Подраздел
        <select>
            <option selected="selected">Выберите объект</option>
            <option>Пункт 1</option>
            <option>Пункт 2</option>
        </select>
    </body>
</html>

WebPlanner/WebPlanner/Views/CashSaving/Cash.cshtml
<html>
    <head>

    </head>
    <body>
        

    </body>
</html>

WebPlanner/WebPlanner/Views/Home/Index.cshtml
@using WebPlanner.Domain.Auxiliary_Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model UserManagerModel
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/_Layout.cshtml";
}
<!doctype html>
<html>
    <head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="@Url.Content("~/css/LogRegForm.css")" rel="stylesheet" type="text/css"/>	
		<link href="@Url.Content("~/css/Background.css")" rel="stylesheet" type="text/css"/>
    </head>
    <body>
		<div class='light x1'></div>
		<div class='light x2'></div>
		<div class='light x3'></div>
		<div class='light x4'></div>
		<div class='light x5'></div>
		<div class='light x6'></div>
		<div class='light x7'></div>
		<div class='light x8'></div>
		<div class='light x9'></div>
		<div class="container" id="container">
	<div class="form-container sign-up-container">
		<form asp-action="Register">
			<h1>Create Account</h1>
			<span>or use your email for registration</span>
			<input type="text" placeholder="Name" asp-for="RegName" />
			<input type="email" placeholder="Email" asp-for="RegEmail" />
			<input type="password" placeholder="Password" asp-for="RegPassword" />
			<button>Sign Up</button>
		</form>
	</div>
	<div class="form-container sign-in-container">
		<form asp-action="Login">
			<h1>Sign in</h1>
			<span>or use your account</span>
			<input type="email" placeholder="Email" asp-for="LoginEmail" />
			<input type="password" placeholder="Password" asp-for="LoginPassword" />
			<a href="#">Forgot your password?</a>
			<button type="submit">Sign In</button>
		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
				<h1>Welcome Back!</h1>
				<p>To keep connected with us please login with your personal info</p>
				<button class="ghost" id="signIn">Sign In</button>
			</div>
			<div class="overlay-panel overlay-right">
				<h1>Hello, Friend!</h1>
				<p>Enter your personal details and start journey with us</p>
				<button class="ghost" id="signUp">Sign Up</button>
			</div>
		</div>
	</div>
</div>		      
    </body>
	<script>
		const signUpButton = document.getElementById('signUp');
		const signInButton = document.getElementById('signIn');
		const container = document.getElementById('container');
		signUpButton.addEventListener('click', () => {
		container.classList.add("right-panel-active");
		});
		signInButton.addEventListener('click', () => {
		container.classList.remove("right-panel-active");
		});
	</script>
</html>

WebPlanner/WebPlanner/Views/MyDay/ShowMyDay.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers;
@{
    ViewBag.Title = "MyDay";
    Layout = "~/Views/_Layout.cshtml";
}
<!Docktype html>
<html>
  <head>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<!--<script src="https://kit.fontawesome.com/a076d05399.js"></script>-->
<link href="@Url.Content("~/css/MyDay.css")" rel="stylesheet" type="text/css"/>
<script src="~/js/MyDayCalendar.js"></script>
  </head>
  <body>
<input placeholder="Select your date" type="text" name="checkIn" id="datepicker" value="" class="calendar"><i class="fas fa-calendar-check icon"></i>
  </body>

</html>

WebPlanner/WebPlanner/Views/_Layout.cshtml
@using WebPlanner.Domain.Enums
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title></title>
  <link href="@Url.Content("~/css/_Layout.css")" rel="stylesheet" type="text/css"/>
</head>

<body>
    <h1>Web planner</h1>

<nav>
  @if(User.Identity.IsAuthenticated)
  {
    <a href="#">Home</a>     
    <a asp-controller="MyDay" asp-action="ShowMyDay">My day</a>
    <a href="#">Wish list</a>
    <a asp-controller="CashSaving" asp-action="Cash">Cash saving</a>
    <a href="@Url.Action("SetUpAccount","Account")">Account</a>
    <div class="animation start-home"></div>
  }
  else
  {
    <a href="" class="disabled">Home</a>
    <a href="" class="disabled">My day</a>
    <a href="" class="disabled">Wish list</a>
    <a href="" class="disabled">Cash saving</a>
    <a href="" class="disabled">Account</a>
    <div class="animation start-home"></div>
  }
        
  
</nav>

<div>
    @RenderBody()
</div>
</body>

</html>